import { AccessDenied } from "@/components/dashboard/access-denied";
import { generateReport } from "@/app/(dashboard)/reports/actions";
import { adminAndReadRoles, hasAnyRole } from "@/lib/auth/authorization";
import { requireSession } from "@/lib/auth/session";
import { prisma } from "@/lib/db/prisma";
import type { ReportType } from "@/types/domain";

const reportCatalog: Array<{
  type: ReportType;
  name: string;
  format: string;
  storage: string;
}> = [
  {
    type: "GROUP_MEMBERSHIP_SNAPSHOT",
    name: "Group Membership Snapshot",
    format: "CSV",
    storage: "Drive + DB link"
  },
  {
    type: "QUARTERLY_ACCESS_REVIEW",
    name: "Quarterly Access Review",
    format: "CSV",
    storage: "Drive + DB link"
  },
  {
    type: "RESTRICTED_ACCESS_EXCEPTIONS",
    name: "Restricted Access Exceptions",
    format: "CSV",
    storage: "Drive + DB link"
  },
  {
    type: "PERMISSION_MATRIX",
    name: "Permission Matrix",
    format: "CSV",
    storage: "Drive + DB link"
  },
  {
    type: "ACCESS_CHANGE_LOG",
    name: "Access & Reconcile Change Log",
    format: "CSV",
    storage: "Drive + DB link"
  }
];

export default async function ReportsPage() {
  const session = await requireSession();

  if (!hasAnyRole(session, adminAndReadRoles)) {
    return (
      <AccessDenied
        title="Reports restricted"
        description="Only authorized internal roles can generate and inspect audit reports."
      />
    );
  }

  const generatedReports = await prisma.generatedReport.findMany({
    orderBy: [{ generatedAt: "desc" }],
    take: 20
  });

  return (
    <div className="stack">
      <section className="hero-card">
        <div className="eyebrow-row">
          <div className="eyebrow">Module 05</div>
          <span className="pill">Evidence archive</span>
        </div>
        <h2>Reports and archival</h2>
        <p>
          Reports are generated as readable CSV files, uploaded automatically to Google Drive, and
          registered with file ID and URL for evidence traceability.
        </p>
      </section>

      <section className="stat-strip">
        <article className="panel stat-card">
          <span>Report types</span>
          <strong>5</strong>
        </article>
        <article className="panel stat-card">
          <span>Generated reports</span>
          <strong>{generatedReports.length}</strong>
        </article>
        <article className="panel stat-card">
          <span>Tracked fields</span>
          <strong>ID + URL</strong>
        </article>
      </section>

      <section className="panel">
        <div className="section-head">
          <div>
            <h3>Report catalog</h3>
            <p className="muted">Each artifact is archived and linked back to the local record, including reconcile activity.</p>
          </div>
          <span className="pill warn">Generate on demand</span>
        </div>
        <table className="table-tight">
          <thead>
            <tr>
              <th>Report</th>
              <th>Format</th>
              <th>Storage</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {reportCatalog.map((report) => (
              <tr key={report.type}>
                <td>{report.name}</td>
                <td>{report.format}</td>
                <td>{report.storage}</td>
                <td>
                  <form action={generateReport}>
                    <input type="hidden" name="reportType" value={report.type} />
                    <button type="submit" className="button-secondary">
                      Generate
                    </button>
                  </form>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="panel">
        <div className="section-head">
          <div>
            <h3>Generated report history</h3>
            <p className="muted">Latest artifacts archived from this environment.</p>
          </div>
          <span className="pill">Generated by {session.email}</span>
        </div>
        <table className="table-tight">
          <thead>
            <tr>
              <th>Generated at</th>
              <th>Report type</th>
              <th>File name</th>
              <th>Generated by</th>
              <th>Drive link</th>
            </tr>
          </thead>
          <tbody>
            {generatedReports.length > 0 ? (
              generatedReports.map((report) => (
                <tr key={report.id}>
                  <td>{report.generatedAt.toISOString().slice(0, 19).replace("T", " ")}</td>
                  <td>{report.reportType === "ACCESS_CHANGE_LOG" ? "Access & Reconcile Change Log" : report.reportType.replaceAll("_", " ")}</td>
                  <td>{report.fileName}</td>
                  <td>{report.generatedByEmail}</td>
                  <td>
                    <a href={report.googleDriveUrl} target="_blank" rel="noreferrer" className="inline-link">
                      Open
                    </a>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={5} className="muted">
                  No generated reports yet.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </section>
    </div>
  );
}
