ALTER TYPE "AppRoleName" ADD VALUE IF NOT EXISTS 'QMS_ACCESS_ADMIN';
ALTER TYPE "AppRoleName" ADD VALUE IF NOT EXISTS 'STRATEGIC_ACCESS_ADMIN';
ALTER TYPE "AppRoleName" ADD VALUE IF NOT EXISTS 'OPERATIONAL_ACCESS_ADMIN';
ALTER TYPE "AppRoleName" ADD VALUE IF NOT EXISTS 'SUPPORT_ACCESS_ADMIN';
